apiVersion: 1

datasources:
  - name: TestOpsPostgres
    type: postgres
    access: proxy
    url: ${PG_HOST}:${PG_PORT}
    database: ${PG_DATABASE}
    user: ${PG_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
